// Norwegian (bokmål) translations. Key = the English text used in t("...").
// `npm test` lists any text that is missing here.
export default {
  // ---------- everyday words ----------
  "Home": "Hjem",
  "Browse": "Utforsk",
  "Search": "Søk",
  "My list": "Min liste",
  "Friends": "Venner",
  "Settings": "Innstillinger",
  "Settings and account": "Innstillinger og konto",
  "About": "Om",
  "Privacy": "Personvern",
  "Movie": "Film",
  "Movies": "Filmer",
  "Series": "Serie",
  "Movies or series": "Filmer eller serier",
  "See all": "Se alle",
  "Load more": "Vis flere",
  "Close": "Lukk",
  "Cancel": "Avbryt",
  "Yes": "Ja",
  "Save": "Lagre",
  "Send": "Send",
  "Add": "Legg til",
  "Remove": "Fjern",
  "Delete": "Slett",
  "Create": "Lag",
  "Rename": "Gi nytt navn",
  "Name": "Navn",
  "You": "Du",
  "Try again": "Prøv igjen",
  "Something went wrong.": "Noe gikk galt.",
  "You're offline. Check your connection.": "Du er frakoblet. Sjekk nettforbindelsen.",
  "This page didn't load": "Siden lastet ikke",
  "Nothing here yet": "Ingenting her ennå",
  "just now": "akkurat nå",
  "{n} min ago": "for {n} min siden",
  "{n} h ago": "for {n} t siden",
  "{n} d ago": "for {n} d siden",
  "{h} h {m} min": "{h} t {m} min",
  "{m} min": "{m} min",
  "{n} season": "{n} sesong",
  "{n} seasons": "{n} sesonger",
  "{n} title": "{n} tittel",
  "{n} titles": "{n} titler",
  "{n} movie": "{n} film",
  "{n} movies": "{n} filmer",
  "1 series": "1 serie",
  "{n} series": "{n} serier",
  "{n} hour": "{n} time",
  "{n} hours": "{n} timer",
  "{n} friend": "{n} venn",
  "{n} friends": "{n} venner",
  "{n} votes": "{n} stemmer",
  "{n} votes on IMDb.": "{n} stemmer på IMDb.",
  "{n} out of 10": "{n} av 10",
  "private": "privat",

  // ---------- frame, footer ----------
  "Movie data from {tmdb}, streaming data from {jw}.": "Filmdata fra {tmdb}, strømmedata fra {jw}.",
  "Pull to refresh": "Dra ned for å oppdatere",
  "Release to refresh": "Slipp for å oppdatere",
  "Nothing on the home screen yet": "Ingenting på forsiden ennå",
  "Switch on some features in js/features.js to fill this page.": "Slå på noen funksjoner i js/features.js for å fylle denne siden.",

  // ---------- tonight ----------
  "What should we watch tonight?": "Hva skal vi se i kveld?",
  "Another one": "En annen",
  "1 title you can watch tonight": "1 tittel dere kan se i kveld",
  "{n} titles you can watch tonight": "{n} titler dere kan se i kveld",
  "On both your watchlists": "På begges ønskelister",
  "On your watchlist": "På ønskelisten din",
  "On {name}'s watchlist": "På ønskelisten til {name}",
  "On {service}, which you both have": "På {service}, som dere begge har",
  "On {service}, which you have": "På {service}, som du har",
  "On {service}, which {name} has": "På {service}, som {name} har",
  "Put a few titles on your watchlist, and pick your streaming services in Settings. Then Playpro picks something you can watch tonight.": "Legg noen titler på ønskelisten, og velg strømmetjenestene dine under Innstillinger. Da finner Playpro noe dere kan se i kveld.",
  "Find something": "Finn noe",

  // ---------- home rows ----------
  "New on your services": "Nytt på tjenestene dine",
  "From your watchlist, since your last visit": "Fra ønskelisten din, siden sist du var her",
  "Ready to watch from your watchlist": "Klart til å se fra ønskelisten din",
  "On services you have": "På tjenester du har",
  "Trending this week": "Populært denne uken",
  "Trending movies": "Populære filmer",
  "Trending series": "Populære serier",
  "Trending right now": "Populært akkurat nå",
  "Popular movies on your services": "Populære filmer på tjenestene dine",
  "Popular series on your services": "Populære serier på tjenestene dine",
  "Newest on your services": "Nyest på tjenestene dine",
  "Coming to cinemas in Norway": "Snart på kino i Norge",
  "In cinemas {date}": "På kino {date}",
  "Picked for you": "Valgt for deg",
  "Because you liked {titles}": "Fordi du likte {titles}",
  "Your friends lately": "Vennene dine i det siste",
  "Your watchlist": "Ønskelisten din",
  "Which streaming services do you have?": "Hvilke strømmetjenester har du?",
  "Pick them once, and Playpro shows what you can watch right now.": "Velg dem én gang, så viser Playpro hva du kan se med en gang.",
  "Add your friend": "Legg til vennen din",
  "See what they're watching and what they thought of it.": "Se hva de ser på, og hva de syntes.",

  // ---------- poster badges ----------
  "You've seen this": "Du har sett denne",
  "Streaming now on one of your services": "Kan strømmes nå på en av tjenestene dine",

  // ---------- title page ----------
  "Poster for {title}": "Plakat for {title}",
  "Average rating on TMDB": "Gjennomsnittlig vurdering på TMDB",
  "Trailer": "Trailer",
  "Where to watch in Norway": "Hvor du kan se den i Norge",
  "Stream": "Strøm",
  "Rent": "Lei",
  "Buy": "Kjøp",
  "Not available to stream, rent or buy in Norway right now.": "Kan ikke strømmes, leies eller kjøpes i Norge akkurat nå.",
  "Streaming data from {link}": "Strømmedata fra {link}",
  "You have this": "Du har denne",
  "On {service}": "På {service}",
  "Streams in Norway": "Strømmes i Norge",
  "Cast": "Skuespillere",
  "More like this": "Mer som dette",
  "RT, {date}": "RT, {date}",
  "Rotten Tomatoes critics score from {date}, via Wikidata": "Kritikerscore fra Rotten Tomatoes, {date}, via Wikidata",
  "Rotten Tomatoes critics score, via Wikidata": "Kritikerscore fra Rotten Tomatoes, via Wikidata",
  "Share": "Del",
  "Shall we watch {title}?": "Skal vi se {title}?",
  "Link copied": "Lenken er kopiert",
  "Couldn't share. Copy the address from the address bar instead.": "Kunne ikke dele. Kopier adressen fra adressefeltet i stedet.",

  // ---------- rating and watchlist ----------
  "Rate": "Vurder",
  "Seen": "Sett",
  "Watchlist": "Ønskeliste",
  "You gave it {n}": "Du ga den {n}",
  "Your rating": "Din vurdering",
  "Short review": "Kort anmeldelse",
  "Optional. Only your friends can see it.": "Valgfritt. Bare vennene dine kan se den.",
  "What did you think?": "Hva syntes du?",
  "Save rating": "Lagre vurdering",
  "Remove from my list": "Fjern fra listen min",
  "Tap a star, or save it as seen without a rating": "Trykk på en stjerne, eller lagre den som sett uten vurdering",
  "Rating saved: {n}/10": "Vurdering lagret: {n}/10",
  "Marked as seen": "Markert som sett",
  "Removed from your list": "Fjernet fra listen din",
  "Removed from your watchlist": "Fjernet fra ønskelisten",
  "Added to your watchlist": "Lagt på ønskelisten",
  "Seen {when}": "Sett {when}",
  "Added {when}": "Lagt til {when}",
  "Rated {n}": "Ga {n}",
  "On your services now": "På tjenestene dine nå",
  "Your year": "Ditt år",
  "Your lists": "Listene dine",
  "Your watchlist is empty": "Ønskelisten er tom",
  "Tap <strong>Watchlist</strong> on a movie or series to save it for later.": "Trykk <strong>Ønskeliste</strong> på en film eller serie for å lagre den til senere.",
  "Nothing rated yet": "Ingenting vurdert ennå",
  "Tap <strong>Rate</strong> on something you've watched. You can also bring your ratings over from IMDb or Letterboxd in Settings.": "Trykk <strong>Vurder</strong> på noe du har sett. Du kan også hente vurderingene dine fra IMDb eller Letterboxd under Innstillinger.",

  // ---------- lists ----------
  "Lists": "Lister",
  "Add to list": "Legg i liste",
  "Add to a list": "Legg i en liste",
  "You don't have any lists yet.": "Du har ingen lister ennå.",
  "New list, e.g. Christmas films": "Ny liste, f.eks. Julefilmer",
  "Name of the new list": "Navn på den nye listen",
  "Added to {list}": "Lagt i {list}",
  "Removed from {list}": "Fjernet fra {list}",
  "Create list": "Lag liste",
  "No lists yet. Make one above, or tap Add to list on any title.": "Ingen lister ennå. Lag en over, eller trykk Legg i liste på en tittel.",
  "Your friends' lists": "Vennenes lister",
  "No shared lists yet": "Ingen delte lister ennå",
  "When your friends share a list, it shows up here.": "Når vennene dine deler en liste, dukker den opp her.",
  "All lists": "Alle lister",
  "This list isn't available": "Denne listen er ikke tilgjengelig",
  "It may be private or deleted.": "Den kan være privat eller slettet.",
  "Your friends can see this list.": "Vennene dine kan se denne listen.",
  "Only you can see this list.": "Bare du kan se denne listen.",
  "A list by {name}": "En liste av {name}",
  "Make private": "Gjør privat",
  "Share with friends": "Del med venner",
  "Delete list": "Slett liste",
  "Delete the list {name}?": "Slette listen {name}?",
  "Rename list": "Gi listen nytt navn",
  "Save name": "Lagre navn",
  "Remove {title} from the list": "Fjern {title} fra listen",
  "This list is empty": "Denne listen er tom",
  "Open a movie or series and tap Add to list.": "Åpne en film eller serie og trykk Legg i liste.",

  // ---------- your year ----------
  "Your {year}": "Ditt {year}",
  "Nothing watched yet this year": "Ingenting sett ennå i år",
  "Rate what you watch, and your year fills up here.": "Vurder det du ser, så fylles året ditt opp her.",
  "You watched {titles}: {movies} and {series}.": "Du så {titles}: {movies} og {series}.",
  "That's {hours} of film.": "Det er {hours} med film.",
  "Your average rating was {avg}.": "Snittvurderingen din var {avg}.",
  "Titles watched per month": "Titler sett per måned",
  "Show as a table": "Vis som tabell",
  "Month": "Måned",
  "Titles": "Titler",
  "{month}: 1 title": "{month}: 1 tittel",
  "{month}: {n} titles": "{month}: {n} titler",
  "Your genres": "Sjangrene dine",
  "Your favourites": "Favorittene dine",

  // ---------- browse and search ----------
  "Everything streaming in Norway, filtered your way.": "Alt som strømmes i Norge, filtrert slik du vil.",
  "Streaming services": "Strømmetjenester",
  "All services": "Alle tjenester",
  "Genre": "Sjanger",
  "All genres": "Alle sjangre",
  "Sort by": "Sorter etter",
  "Most popular": "Mest populære",
  "Highest rated": "Best vurdert",
  "Newest": "Nyeste",
  "Nothing matches": "Ingen treff",
  "Try another genre, more services, or switch off the IMDb filter.": "Prøv en annen sjanger, flere tjenester, eller slå av IMDb-filteret.",
  "Titles didn't load": "Titlene lastet ikke",
  "Movies, series, actors…": "Filmer, serier, skuespillere…",
  "Search movies and series": "Søk etter filmer og serier",
  "No results": "Ingen treff",
  "Nothing matched “{q}”. Check the spelling, or try the original title or an IMDb link.": "Ingenting passet til «{q}». Sjekk stavingen, eller prøv originaltittelen eller en IMDb-lenke.",
  "Nothing matched with the year, so here are all years. {year} comes first.": "Ingenting passet med årstallet, så her er alle år. {year} kommer først.",
  "Nothing matched exactly. These are close matches.": "Ingenting passet nøyaktig. Dette er de nærmeste treffene.",
  "Search didn't work": "Søket fungerte ikke",

  // ---------- friends ----------
  "Average rating from your friends": "Gjennomsnittlig vurdering fra vennene dine",
  "What you thought": "Hva dere syntes",
  "rated it {n}": "ga den {n}",
  "watched it": "så den",
  "wants to watch it": "vil se den",
  "React": "Reager",
  "Comment": "Kommenter",
  "Write a comment": "Skriv en kommentar",
  "Write a comment…": "Skriv en kommentar…",
  "Find people by username": "Finn folk etter brukernavn",
  "Find people by username…": "Finn folk etter brukernavn…",
  "Friend requests": "Venneforespørsler",
  "Accept": "Godta",
  "Decline": "Avslå",
  "Lately": "I det siste",
  "When your friends rate something, it shows up here.": "Når vennene dine vurderer noe, dukker det opp her.",
  "Add a friend to see what they're watching.": "Legg til en venn for å se hva de ser på.",
  "Your friends": "Vennene dine",
  "No friends yet. Search for their username above, or send them the app link and invite code.": "Ingen venner ennå. Søk etter brukernavnet deres over, eller send dem lenken og invitasjonskoden.",
  "Waiting for an answer": "Venter på svar",
  "You're now friends": "Nå er dere venner",
  "Friend request sent": "Venneforespørsel sendt",
  "Remove {name} as a friend?": "Fjerne {name} som venn?",
  "There's already a request between you two": "Det finnes allerede en forespørsel mellom dere",
  "Requested": "Forespurt",
  "No one called “{q}”.": "Ingen som heter «{q}».",
  "No such member": "Fant ikke medlemmet",
  "Maybe they changed their username.": "Kanskje de har byttet brukernavn.",
  "Add friend": "Legg til venn",
  "Wants to be your friend. Answer on the Friends page.": "Vil bli venn med deg. Svar på Venner-siden.",
  "Member since {date}": "Medlem siden {date}",
  "{seen} seen, average rating {avg}, {list} on the watchlist.": "{seen} sett, snittvurdering {avg}, {list} på ønskelisten.",
  "Their lists are private": "Listene deres er private",
  "Only friends can see each other's ratings and watchlists.": "Bare venner kan se hverandres vurderinger og ønskelister.",

  // ---------- settings ----------
  "Username": "Brukernavn",
  "Other members see this name when they look for friends.": "Andre medlemmer ser dette navnet når de leter etter venner.",
  "Username saved": "Brukernavnet er lagret",
  "Language": "Språk",
  "Changes the app's buttons and menus, and movie descriptions where TMDB has them in Norwegian.": "Endrer knapper og menyer, og filmbeskrivelser der TMDB har dem på norsk.",
  "Your data and privacy": "Dine data og personvern",
  "You own your data. The {link} says exactly what is stored and who can see it.": "Du eier dataene dine. {link} sier nøyaktig hva som lagres og hvem som kan se det.",
  "privacy notice": "Personvernerklæringen",
  "Download my data": "Last ned dataene mine",
  "Delete my account": "Slett kontoen min",
  "Sign out": "Logg ut",
  "About Playpro": "Om Playpro",
  "Delete your account?": "Slette kontoen din?",
  "This permanently deletes your login, lists, ratings, reviews, comments and friendships. It can't be undone.": "Dette sletter innloggingen, listene, vurderingene, anmeldelsene, kommentarene og vennskapene dine for godt. Det kan ikke angres.",
  "Type {name} to confirm": "Skriv {name} for å bekrefte",
  "Delete everything": "Slett alt",
  "The name doesn't match": "Navnet stemmer ikke",
  "Your account and data are deleted": "Kontoen og dataene dine er slettet",
  "Your streaming services": "Strømmetjenestene dine",
  "Pick what you pay for. Playpro then shows what you can watch right away.": "Velg det du betaler for. Da viser Playpro hva du kan se med en gang.",
  "Show all {n} services in Norway": "Vis alle {n} tjenester i Norge",
  "Streaming services saved": "Strømmetjenestene er lagret",
  "Profile picture": "Profilbilde",
  "Other members see it next to your name. It's cropped to a square and made small before it's saved.": "Andre medlemmer ser det ved siden av navnet ditt. Det beskjæres til et kvadrat og gjøres lite før det lagres.",
  "Choose picture": "Velg bilde",
  "Change picture": "Bytt bilde",
  "Remove picture": "Fjern bildet",
  "Profile picture saved": "Profilbildet er lagret",
  "Profile picture removed": "Profilbildet er fjernet",
  "That file isn't a picture": "Den filen er ikke et bilde",
  "That picture is too big (over 25 MB)": "Bildet er for stort (over 25 MB)",
  "Couldn't read that picture. Try a JPG or PNG.": "Kunne ikke lese bildet. Prøv en JPG eller PNG.",
  "Bring your ratings": "Ta med vurderingene dine",
  "Choose CSV file": "Velg CSV-fil",
  "Matching titles: {done} of {total}": "Finner titler: {done} av {total}",
  "Added {added}. Already in Playpro: {skipped}. Not found: {missing}.": "Lagt til: {added}. Fantes allerede i Playpro: {skipped}. Ikke funnet: {missing}.",
  "Import finished": "Importen er ferdig",
  "That file doesn't look like an IMDb or Letterboxd export.": "Den filen ser ikke ut som en eksport fra IMDb eller Letterboxd.",

  // ---------- sign in ----------
  "Sign in": "Logg inn",
  "Create account": "Lag konto",
  "Playpro shows where to stream it in Norway, and what your friends thought of it.": "Playpro viser hvor du kan strømme det i Norge, og hva vennene dine syntes.",
  "Email": "E-post",
  "Password": "Passord",
  "Forgot password?": "Glemt passordet?",
  "3 to 20 letters, numbers or _, and nothing rude. Other members can see it.": "3 til 20 bokstaver, tall eller _, og ingenting frekt. Andre medlemmer kan se det.",
  "Only used to sign in. Nobody else sees it.": "Brukes bare til å logge inn. Ingen andre ser den.",
  "At least 8 characters.": "Minst 8 tegn.",
  "Invite code": "Invitasjonskode",
  "Ask the person who sent you the link.": "Spør den som sendte deg lenken.",
  "I have read the {link} and want an account.": "Jeg har lest {link} og vil ha en konto.",
  "Enter your email and we'll send you a link to choose a new password.": "Skriv inn e-posten din, så sender vi en lenke der du kan velge nytt passord.",
  "Send reset link": "Send lenke",
  "Back to sign in": "Tilbake til innlogging",
  "Reset password": "Nytt passord",
  "Check your email": "Sjekk e-posten din",
  "We sent a confirmation link to {email}. Open it on this device to finish.": "Vi har sendt en bekreftelseslenke til {email}. Åpne den på denne enheten for å fullføre.",
  "If an account exists for {email}, a reset link is on its way. Open it on this device.": "Hvis det finnes en konto for {email}, er en lenke på vei. Åpne den på denne enheten.",
  "Wrong email or password.": "Feil e-post eller passord.",
  "New password": "Nytt passord",
  "Choose a new password": "Velg et nytt passord",
  "Save password": "Lagre passordet",
  "Password saved": "Passordet er lagret",
  "That username is taken. Try another one.": "Brukernavnet er tatt. Prøv et annet.",
  "Sign-up refused. Check the invite code.": "Registreringen ble avvist. Sjekk invitasjonskoden.",
  "The database isn't set up yet. Run supabase/schema.sql in the SQL Editor of your Playpro Supabase project (README, step 2).": "Databasen er ikke satt opp ennå. Kjør supabase/schema.sql i SQL Editor i Playpro-prosjektet ditt i Supabase (README, steg 2).",

  // ---------- privacy notice ----------
  "How Playpro handles your data": "Slik behandler Playpro dataene dine",
  "Playpro is a small, non-commercial app for a group of friends. There are no ads, no analytics and no tracking.": "Playpro er en liten, ikke-kommersiell app for en vennegjeng. Det er ingen reklame, ingen analyse og ingen sporing.",
  "Who is responsible": "Hvem som er ansvarlig",
  "{owner} runs Playpro and is responsible for your data (the \"controller\" under GDPR). Contact: {email}.": "{owner} driver Playpro og er ansvarlig for dataene dine (behandlingsansvarlig etter GDPR). Kontakt: {email}.",
  "What we store": "Hva vi lagrer",
  "<strong>Account:</strong> your email address and password. The password is stored scrambled (hashed), so nobody can read it.": "<strong>Konto:</strong> e-postadressen og passordet ditt. Passordet lagres kryptert (hashet), så ingen kan lese det.",
  "<strong>Profile:</strong> your username, which streaming services you have, and a profile picture if you choose to add one (shrunk to a small square before it's saved).": "<strong>Profil:</strong> brukernavnet ditt, hvilke strømmetjenester du har, og et profilbilde hvis du velger å legge til et (gjort om til et lite kvadrat før det lagres).",
  "<strong>Your activity:</strong> your watchlist, what you've seen and when, your ratings and short reviews, lists you make, and comments and reactions you add.": "<strong>Aktiviteten din:</strong> ønskelisten din, hva du har sett og når, vurderingene og de korte anmeldelsene dine, lister du lager, og kommentarer og reaksjoner du legger til.",
  "<strong>Friends:</strong> who you've sent or accepted friend requests to.": "<strong>Venner:</strong> hvem du har sendt eller godtatt venneforespørsler til.",
  "We never ask for your real name, birthday or location. A profile picture is optional, and you can remove it at any time in Settings.": "Vi spør aldri om ditt ekte navn, fødselsdag eller hvor du er. Profilbilde er valgfritt, og du kan fjerne det når som helst under Innstillinger.",
  "Why, and on what basis": "Hvorfor, og på hvilket grunnlag",
  "Only to run the app you signed up for: signing you in, keeping your lists, and sharing ratings with the friends you choose (GDPR article 6(1)(b), providing a service you asked for). Nothing is sold, shared for marketing or used to profile you.": "Bare for å drive appen du har meldt deg på: logge deg inn, ta vare på listene dine og dele vurderinger med vennene du velger (GDPR artikkel 6 nr. 1 bokstav b, å levere en tjeneste du har bedt om). Ingenting selges, deles til markedsføring eller brukes til å profilere deg.",
  "Who can see what": "Hvem som kan se hva",
  "Other members can see your <strong>username</strong> and <strong>profile picture</strong> so they can find you and send you a friend request.": "Andre medlemmer kan se <strong>brukernavnet</strong> og <strong>profilbildet</strong> ditt, så de kan finne deg og sende en venneforespørsel.",
  "Only <strong>friends you have accepted</strong> can see your watchlist, ratings, reviews, shared lists, and the comments and reactions on your ratings.": "Bare <strong>venner du har godtatt</strong> kan se ønskelisten, vurderingene, anmeldelsene og de delte listene dine, og kommentarene og reaksjonene på vurderingene dine.",
  "Lists you mark as private are only visible to you. Nobody else can see your email address.": "Lister du gjør private, ser bare du. Ingen andre kan se e-postadressen din.",
  "Services that help run Playpro": "Tjenester som hjelper til med å drive Playpro",
  "<strong>Supabase</strong> stores accounts and data on servers in the EU (acting as our data processor).": "<strong>Supabase</strong> lagrer kontoer og data på servere i EU (som vår databehandler).",
  "<strong>GitHub Pages</strong>, which serves the app's files, sees normal technical data such as your IP address.": "<strong>GitHub Pages</strong>, som leverer appens filer, ser vanlige tekniske data som IP-adressen din.",
  "<strong>TMDB</strong> (themoviedb.org): your device fetches movie information, posters and streaming data directly from TMDB, so TMDB sees your IP address. We don't send them anything about you.": "<strong>TMDB</strong> (themoviedb.org): enheten din henter filminformasjon, plakater og strømmedata direkte fra TMDB, så TMDB ser IP-adressen din. Vi sender dem ingenting om deg.",
  "<strong>IMDb and Rotten Tomatoes scores</strong> are copied into our own database twice a week (from IMDb's public data files and Wikidata). Your device never contacts IMDb or Wikidata for them.": "<strong>Vurderinger fra IMDb og Rotten Tomatoes</strong> kopieres inn i vår egen database to ganger i uken (fra IMDbs offentlige datafiler og Wikidata). Enheten din kontakter aldri IMDb eller Wikidata for dem.",
  "Trailer, IMDb and Rotten Tomatoes buttons open those websites in a new tab; their own privacy policies apply there.": "Knappene for trailer, IMDb og Rotten Tomatoes åpner de nettstedene i en ny fane; der gjelder deres egne personvernregler.",
  "Cookies and local storage": "Informasjonskapsler og lokal lagring",
  "Playpro doesn't use cookies. Your browser keeps your login, your language choice and a copy of movie information (so the app opens faster). This is strictly necessary for the app to work, so no cookie banner is needed.": "Playpro bruker ikke informasjonskapsler. Nettleseren din tar vare på innloggingen, språkvalget og en kopi av filminformasjon (så appen åpner raskere). Dette er strengt nødvendig for at appen skal virke, så det trengs ikke noe samtykkebanner.",
  "How long we keep it": "Hvor lenge vi tar vare på dem",
  "Until you delete your account. Deleting it (Settings, then Delete my account) removes your data immediately.": "Til du sletter kontoen din. Sletter du den (Innstillinger, så Slett kontoen min), fjernes dataene dine med en gang.",
  "Your rights": "Rettighetene dine",
  "<strong>See and download</strong> your data: Settings, then Download my data.": "<strong>Se og last ned</strong> dataene dine: Innstillinger, så Last ned dataene mine.",
  "<strong>Correct</strong> it: change your username, lists and ratings at any time.": "<strong>Rette</strong> dem: endre brukernavn, lister og vurderinger når som helst.",
  "<strong>Delete</strong> it: Settings, then Delete my account.": "<strong>Slette</strong> dem: Innstillinger, så Slett kontoen min.",
  "<strong>Object or ask questions:</strong> email {email}.": "<strong>Protestere eller spørre:</strong> send e-post til {email}.",
  "<strong>Complain</strong> to a data protection authority, in Norway {link}.": "<strong>Klage</strong> til et datatilsyn, i Norge {link}.",
  "Last updated {date}.": "Sist oppdatert {date}.",

  // ---------- about ----------
  "A private, non-commercial app for friends: find something to watch tonight, see where it streams in Norway, rate what you've seen and compare notes.": "En privat, ikke-kommersiell app for venner: finn noe å se i kveld, se hvor det strømmes i Norge, vurder det du har sett og sammenlign.",
  "Credits": "Takk til",
  "Streaming availability is provided by JustWatch through TMDB.": "Strømmedata kommer fra JustWatch via TMDB.",
  "IMDb ratings come from IMDb's non-commercial datasets. Playpro is not affiliated with IMDb.": "IMDb-vurderingene kommer fra IMDbs ikke-kommersielle datasett. Playpro er ikke tilknyttet IMDb.",
  "Rotten Tomatoes scores come from Wikidata (CC0), with the date they were recorded. Playpro is not affiliated with Rotten Tomatoes or Fandango.": "Rotten Tomatoes-scorer kommer fra Wikidata (CC0), med datoen de ble registrert. Playpro er ikke tilknyttet Rotten Tomatoes eller Fandango.",
  "Typefaces: Anybody and Familjen Grotesk, under the SIL Open Font License.": "Skrifter: Anybody og Familjen Grotesk, under SIL Open Font License.",
  "Read the privacy notice": "Les personvernerklæringen",
  // feature template (js/features/_template)
  "Hello": "Hei",
  "A row from the template feature.": "En rad fra malen.",
  "Fun fact": "Visste du?",
  "{title} has {n} credited actors.": "{title} har {n} oppførte skuespillere.",
  "This page comes from the template feature.": "Denne siden kommer fra malen.",
  // username rules
  "Use 3 to 20 letters, numbers or _.": "Bruk 3 til 20 bokstaver, tall eller _.",
  "That username isn't allowed. Pick another one.": "Det brukernavnet er ikke lov. Velg et annet.",
  "Choose a new username": "Velg et nytt brukernavn",
  "Your username doesn't follow Playpro's rules for names. Pick a new one to keep using the app. Your lists, ratings and friends stay as they are.": "Brukernavnet ditt følger ikke Playpros regler for navn. Velg et nytt for å fortsette å bruke appen. Listene, vurderingene og vennene dine blir som før.",
  "New username": "Nytt brukernavn",
  "Save username": "Lagre brukernavn",
  // cinema and coming soon
  "At the cinema": "På kino",
  "Cinema": "Kino",
  "Coming soon": "Kommer snart",
  "Coming to your services": "Kommer til tjenestene dine",
  "Films in Norwegian cinemas now, and the ones opening soon.": "Filmer på norske kinoer nå, og de som har premiere snart.",
  "Films to stream or rent soon": "Filmer du snart kan strømme eller leie",
  "From {date}": "Fra {date}",
  "Go to Settings": "Gå til Innstillinger",
  "In Norwegian cinemas since {date}.": "På norske kinoer siden {date}.",
  "New seasons and new series on the services you have.": "Nye sesonger og nye serier på tjenestene du har.",
  "New series on {service}": "Ny serie på {service}",
  "New, {date}": "Ny, {date}",
  "No premieres listed yet": "Ingen premierer er meldt ennå",
  "Nothing announced yet": "Ingenting er meldt ennå",
  "Nothing listed for Norwegian cinemas right now": "Ingenting er oppført på norske kinoer akkurat nå",
  "Open a film to find showtimes and tickets on Filmweb, which sells tickets for most cinemas in Norway.": "Åpne en film for å finne visninger og billetter på Filmweb, som selger billetter til de fleste kinoer i Norge.",
  "Opens Filmweb, which sells tickets for most cinemas in Norway.": "Åpner Filmweb, som selger billetter til de fleste kinoer i Norge.",
  "Opens in Norwegian cinemas on {date}.": "Har premiere på norske kinoer {date}.",
  "Pick your streaming services in Settings, and new seasons and series on them show up here.": "Velg strømmetjenestene dine i Innstillinger, så dukker nye sesonger og serier på dem opp her.",
  "Season {n} on {service}": "Sesong {n} på {service}",
  "Season {n}, {date}": "Sesong {n}, {date}",
  "Showing now": "Går nå",
  "Showtimes and tickets": "Visninger og billetter",
  "Since {date}": "Siden {date}",
  "Streaming": "Strømming",
  "This didn't load": "Dette lastet ikke",
  // invite friends (administrator)
  "<strong>Invite codes:</strong> if you joined with a personal invite code, which account used it, so the administrator who made the code can see that you joined. Codes the administrator makes are stored with an optional note about who they're for.": "<strong>Invitasjonskoder:</strong> hvis du ble med via en personlig invitasjonskode, lagres hvilken konto som brukte den, slik at administratoren som laget koden ser at du ble med. Koder administratoren lager, lagres med et valgfritt notat om hvem de er til.",
  "Cancelled": "Avbrutt",
  "Create invite code": "Lag invitasjonskode",
  "Expired": "Utløpt",
  "Invite code cancelled": "Invitasjonskoden er avbrutt",
  "Invite copied. Paste it in a message.": "Invitasjonen er kopiert. Lim den inn i en melding.",
  "Invite friends": "Inviter venner",
  "Join me on Playpro! Open the link and create an account. Your invite code is {code}.": "Bli med på Playpro! Åpne lenken og lag en konto. Invitasjonskoden din er {code}.",
  "New invite code": "Ny invitasjonskode",
  "Share invite": "Del invitasjonen",
  "Used by {name}, {date}": "Brukt av {name}, {date}",
  "Waiting, until {date}": "Venter, til {date}",
  "Who is it for? (optional)": "Hvem er den til? (valgfritt)",
  "You're the administrator. Each invite code works for one person, for 7 days.": "Du er administrator. Hver invitasjonskode fungerer for én person, i 7 dager.",
  "a deleted account": "en slettet konto",
  // IMDb export guides
  "Pick the file you download from IMDb or {lb} (Settings, then Import & Export) with your ratings or watchlist. Titles you already have in Playpro are kept as they are.": "Velg filen du laster ned fra IMDb eller {lb} (Settings, så Import & Export) med vurderingene eller ønskelisten din. Titler du allerede har i Playpro, blir som de er.",
  "How to get the file from IMDb on a computer": "Slik henter du filen fra IMDb på en datamaskin",
  "How to get the file from IMDb on a phone": "Slik henter du filen fra IMDb på mobilen",
  "Go to {link} and sign in. (Want your watchlist instead? Click your name at the top right, then <strong>Your watchlist</strong>.)": "Gå til {link} og logg inn. (Vil du heller ha ønskelisten? Klikk navnet ditt øverst til høyre, så <strong>Your watchlist</strong>.)",
  "Click <strong>Export</strong> at the top of the list. On some screens it's in the <strong>⋮</strong> menu.": "Klikk <strong>Export</strong> øverst i listen. På noen skjermer ligger den i <strong>⋮</strong>-menyen.",
  "IMDb gets the file ready, which takes about a minute. Open {link} and click <strong>Download</strong> next to it. Not there yet? Reload the page.": "IMDb gjør filen klar, det tar omtrent et minutt. Åpne {link} og klikk <strong>Download</strong> ved siden av den. Ikke der ennå? Last inn siden på nytt.",
  "The file ends in <strong>.csv</strong> and lands in your <strong>Downloads</strong> folder.": "Filen slutter på <strong>.csv</strong> og havner i mappen <strong>Nedlastinger</strong> (Downloads).",
  "Come back here, click <strong>Choose CSV file</strong> and pick it.": "Kom tilbake hit, klikk <strong>Velg CSV-fil</strong> og velg den.",
  "The IMDb app can't do this, so use the browser: open {link} in <strong>Safari</strong> (iPhone) or <strong>Chrome</strong> (Android) and sign in.": "IMDb-appen kan ikke gjøre dette, så bruk nettleseren: åpne {link} i <strong>Safari</strong> (iPhone) eller <strong>Chrome</strong> (Android) og logg inn.",
  "Switch to the desktop version of the page. iPhone: tap <strong>aA</strong> in the address bar, then <strong>Request Desktop Website</strong>. Android: tap <strong>⋮</strong> and tick <strong>Desktop site</strong>.": "Bytt til datamaskinversjonen av siden. iPhone: trykk <strong>aA</strong> i adressefeltet, så <strong>Be om skrivebordsnettsted</strong>. Android: trykk <strong>⋮</strong> og huk av for <strong>Datamaskinversjon</strong> (Desktop site).",
  "Tap <strong>Export</strong> at the top of the list (or <strong>⋮</strong>, then <strong>Export</strong>).": "Trykk <strong>Export</strong> øverst i listen (eller <strong>⋮</strong>, så <strong>Export</strong>).",
  "Wait about a minute, open {link} (still as the desktop version) and tap <strong>Download</strong>. If the phone asks, tap <strong>Download</strong> again.": "Vent omtrent et minutt, åpne {link} (fortsatt som datamaskinversjon) og trykk <strong>Download</strong>. Hvis mobilen spør, trykk <strong>Last ned</strong>.",
  "iPhone: the file is in the <strong>Files</strong> app, under <strong>Downloads</strong>. Android: in <strong>Downloads</strong>.": "iPhone: filen ligger i <strong>Filer</strong>-appen, under <strong>Nedlastinger</strong>. Android: i <strong>Nedlastinger</strong>.",
  "Come back here, tap <strong>Choose CSV file</strong>, find the file in Downloads and pick it.": "Kom tilbake hit, trykk <strong>Velg CSV-fil</strong>, finn filen i Nedlastinger og velg den.",
};
